// This file is part of midnightntwrk/example-bboard.
// Copyright (C) Midnight Foundation
// SPDX-License-Identifier: Apache-2.0
// Licensed under the Apache License, Version 2.0 (the "License");
// You may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*
 * This file is the main driver for the Midnight course completion credential example.
 * The entry point is the run function, at the end of the file.
 * We expect the startup files (testnet-remote.ts, standalone.ts, etc.) to
 * call run with some specific configuration that sets the network addresses
 * of the servers this file relies on.
 */

import { createInterface, type Interface } from 'node:readline/promises';
import { stdin as input, stdout as output } from 'node:process';
import { WebSocket } from 'ws';
import {
  CourseCredentialAPI,
  type CourseCredentialDerivedState,
  courseCredentialPrivateStateKey,
  type CourseCredentialProviders,
  type DeployedCourseCredentialContract,
  type PrivateStateId,
} from '../../api/src/index';
import { type WalletFacade } from '@midnight-ntwrk/wallet-sdk-facade';
import { ledger, type Ledger, State } from '../../contract/src/managed/course-credential/contract/index.js';
import { NodeZkConfigProvider } from '@midnight-ntwrk/midnight-js-node-zk-config-provider';
import { indexerPublicDataProvider } from '@midnight-ntwrk/midnight-js-indexer-public-data-provider';
import { httpClientProofProvider } from '@midnight-ntwrk/midnight-js-http-client-proof-provider';
import { type Logger } from 'pino';
import { type Config, StandaloneConfig } from './config.js';
import { levelPrivateStateProvider } from '@midnight-ntwrk/midnight-js-level-private-state-provider';
import { type ContractAddress } from '@midnight-ntwrk/midnight-js-protocol/compact-runtime';
import { assertIsContractAddress, toHex, fromHex } from '@midnight-ntwrk/midnight-js-utils';
import { TestEnvironment } from '@midnight-ntwrk/testkit-js';
import { MidnightWalletProvider } from './midnight-wallet-provider';
import { randomBytes } from '../../api/src/utils';
import { unshieldedToken } from '@midnight-ntwrk/midnight-js-protocol/ledger';
import { syncWallet, waitForUnshieldedFunds } from './wallet-utils';
import { generateDust } from './generate-dust';
import { CourseCredentialPrivateState } from '../../contract/src/witnesses.js';

// @ts-expect-error: It's needed to enable WebSocket usage through apollo
globalThis.WebSocket = WebSocket;

/* **********************************************************************
 * getCourseCredentialLedgerState: a helper that queries the current state of
 * the data on the ledger, for a specific course completion credential contract.
 * Note that the Ledger type returned here is not some generic,
 * abstract ledger object, but specifically the type generated by
 * the Compact compiler to correspond to the ledger declaration
 * in the course completion credential contract.
 */

export const getCourseCredentialLedgerState = async (
  providers: CourseCredentialProviders,
  contractAddress: ContractAddress,
): Promise<Ledger | null> => {
  assertIsContractAddress(contractAddress);
  const contractState = await providers.publicDataProvider.queryContractState(contractAddress);
  return contractState != null ? ledger(contractState.data) : null;
};

/* **********************************************************************
 * deployOrJoin: returns a contract, by prompting the user about
 * whether to deploy a new one or join an existing one and then
 * calling the appropriate helper.
 */

const DEPLOY_OR_JOIN_QUESTION = `
You can do one of the following:
  1. Deploy a new course completion credential contract (act as an issuer)
  2. Join an existing course completion credential contract (act as a verifier)
  3. Exit
Which would you like to do? `;

const deployOrJoin = async (
  providers: CourseCredentialProviders,
  rli: Interface,
  logger: Logger,
): Promise<CourseCredentialAPI | null> => {
  let api: CourseCredentialAPI | null = null;

  while (true) {
    const choice = await rli.question(DEPLOY_OR_JOIN_QUESTION);
    switch (choice) {
      case '1':
        api = await CourseCredentialAPI.deploy(providers, logger);
        logger.info(`Deployed contract at address: ${api.deployedContractAddress}`);
        return api;
      case '2':
        api = await CourseCredentialAPI.join(
          providers,
          await rli.question('What is the contract address (in hex)? '),
          logger,
        );
        logger.info(`Joined contract at address: ${api.deployedContractAddress}`);
        return api;
      case '3':
        logger.info('Exiting...');
        return null;
      default:
        logger.error(`Invalid choice: ${choice}`);
    }
  }
};

/* **********************************************************************
 * displayLedgerState: shows the values of each of the fields declared
 * by the contract to be in the ledger state of the course credential.
 * The student commitment is displayed (it is public), but the student's
 * identifier itself never appears anywhere on the ledger.
 */

const displayLedgerState = async (
  providers: CourseCredentialProviders,
  deployedCourseCredentialContract: DeployedCourseCredentialContract,
  logger: Logger,
): Promise<void> => {
  const contractAddress = deployedCourseCredentialContract.deployTxData.public.contractAddress;
  const ledgerState = await getCourseCredentialLedgerState(providers, contractAddress);
  if (ledgerState === null) {
    logger.info(`There is no course completion credential contract deployed at ${contractAddress}`);
  } else {
    const credentialState = ledgerState.state === State.ISSUED ? 'issued' : 'vacant';
    const latestCourse = !ledgerState.course.is_some ? 'none' : ledgerState.course.value;
    const commitment = !ledgerState.studentCommitment.is_some ? 'none' : toHex(ledgerState.studentCommitment.value);
    logger.info(`Current state is: '${credentialState}'`);
    logger.info(`Current course is: '${latestCourse}'`);
    logger.info(`Current student commitment is: '${commitment}'`);
    logger.info(`Current sequence is: ${ledgerState.sequence}`);
    logger.info(`Current issuer is: '${toHex(ledgerState.issuer)}'`);
  }
};

/* **********************************************************************
 * displayPrivateState: shows the hex-formatted value of the secret key.
 */

const displayPrivateState = async (providers: CourseCredentialProviders, logger: Logger): Promise<void> => {
  const privateState = await providers.privateStateProvider.get(courseCredentialPrivateStateKey);
  if (privateState === null) {
    logger.info(`There is no existing course credential private state`);
  } else {
    logger.info(`Current secret key is: ${toHex(privateState.secretKey)}`);
  }
};

/* **********************************************************************
 * displayDerivedState: shows the values of derived state which is made
 * by combining the ledger state with private state. In this example, the
 * derived state compares the issuer's key with the private secret key to
 * determine if the current user is the issuer of the current credential.
 */

const displayDerivedState = (ledgerState: CourseCredentialDerivedState | undefined, logger: Logger) => {
  if (ledgerState === undefined) {
    logger.info(`No course completion credential state currently available`);
  } else {
    const credentialState = ledgerState.state === State.ISSUED ? 'issued' : 'vacant';
    const latestCourse = ledgerState.state === State.ISSUED ? ledgerState.course : 'none';
    logger.info(`Current state is: '${credentialState}'`);
    logger.info(`Current course is: '${latestCourse}'`);
    logger.info(`Current issuer is: '${ledgerState.isIssuer ? 'you' : 'not you'}'`);
  }
};

/* **********************************************************************
 * issueCredentialFlow: prompts the issuer for the course name and the
 * student's private identifier. The salt is generated automatically and
 * the full credential bundle is printed so it can be shared with the
 * student (and, in turn, with a verifier).
 */

const issueCredentialFlow = async (api: CourseCredentialAPI, rli: Interface, logger: Logger): Promise<void> => {
  const course = await rli.question('What is the name of the completed course? ');
  const studentIdentifier = await rli.question(
    'What is the student identifier (name, email, or ID)? This value stays private and is never written to the ledger. ',
  );
  const { salt } = await api.issueCredential(course, studentIdentifier);
  logger.info(`Issued credential for course: '${course}'`);
  logger.info('Credential issued. Share the following bundle with the student:');
  logger.info(`  Contract address: ${api.deployedContractAddress}`);
  logger.info(`  Course:            ${course}`);
  logger.info(`  Student identifier: ${studentIdentifier}`);
  logger.info(`  Salt:              ${toHex(salt)}`);
};

/* **********************************************************************
 * verifyCredentialFlow: prompts the verifier for the course name, the
 * student identifier and salt that the student revealed, then verifies
 * the on-chain credential locally. Nothing is written to the ledger.
 */

const verifyCredentialFlow = async (api: CourseCredentialAPI, rli: Interface, logger: Logger): Promise<void> => {
  const course = await rli.question('What course was the student claimed to complete? ');
  const studentIdentifier = await rli.question('What is the student identifier the student revealed to you? ');
  const salt = fromHex(await rli.question('What is the salt the student revealed to you (hex)? '));

  const result = await api.verifyCredential(course, studentIdentifier, salt);

  if (result.valid) {
    logger.info(`Credential verified: student completed '${result.course}'`);
  } else {
    const reason = {
      'no-active-credential': 'no credential is currently issued for this contract',
      'course-mismatch': 'the on-chain credential is for a different course',
      'commitment-mismatch': 'the identifier/salt do not match the on-chain commitment',
    }[result.reason];
    logger.info(`Credential NOT verified: ${reason}`);
  }
};

/* **********************************************************************
 * mainLoop: the main interactive menu of the course completion credential CLI.
 * Before starting the loop, the user is prompted to deploy a new
 * contract or join an existing one.
 */

const MAIN_LOOP_QUESTION = `
You can do one of the following:
  1. Issue a course completion credential (issuer)
  2. Revoke the current credential (issuer)
  3. Verify a credential (verifier)
  4. Display the current ledger state (known by everyone)
  5. Display the current private state (known only to this DApp instance)
  6. Display the current derived state (known only to this DApp instance)
  7. Exit
Which would you like to do? `;

const mainLoop = async (providers: CourseCredentialProviders, rli: Interface, logger: Logger): Promise<void> => {
  const api = await deployOrJoin(providers, rli, logger);
  if (api === null) {
    return;
  }
  let currentState: CourseCredentialDerivedState | undefined;
  const stateObserver = {
    next: (state: CourseCredentialDerivedState) => (currentState = state),
  };
  const subscription = api.state$.subscribe(stateObserver);
  try {
    while (true) {
      const choice = await rli.question(MAIN_LOOP_QUESTION);
      try {
        switch (choice) {
          case '1':
            await issueCredentialFlow(api, rli, logger);
            break;
          case '2':
            await api.revokeCredential();
            logger.info('Credential revoked.');
            break;
          case '3':
            await verifyCredentialFlow(api, rli, logger);
            break;
          case '4':
            await displayLedgerState(providers, api.deployedContract, logger);
            break;
          case '5':
            await displayPrivateState(providers, logger);
            break;
          case '6':
            displayDerivedState(currentState, logger);
            break;
          case '7':
            logger.info('Exiting...');
            return;
          default:
            logger.error(`Invalid choice: ${choice}`);
        }
      } catch (e) {
        logError(logger, e);
        logger.info('Returning to main menu...');
      }
    }
  } finally {
    // While we allow errors to bubble up to the 'run' function, we will always need to dispose of the state
    // subscription when we exit.
    subscription.unsubscribe();
  }
};

/* ***********************************************************************
 * This seed gives access to tokens minted in the genesis block of a local development node - only
 * used in standalone networks to build a wallet with initial funds.
 */
const GENESIS_MINT_WALLET_SEED = '0000000000000000000000000000000000000000000000000000000000000001';

/* **********************************************************************
 * buildWallet: unless running in a standalone (offline) mode,
 * prompt the user to tell us whether to create a new wallet
 * or recreate one from a prior seed.
 */

const WALLET_LOOP_QUESTION = `
You can do one of the following:
  1. Build a fresh wallet
  2. Build wallet from a seed
  3. Exit
Which would you like to do? `;

const buildWallet = async (config: Config, rli: Interface, logger: Logger): Promise<string | undefined> => {
  if (config instanceof StandaloneConfig) {
    return GENESIS_MINT_WALLET_SEED;
  }
  while (true) {
    const choice = await rli.question(WALLET_LOOP_QUESTION);
    switch (choice) {
      case '1':
        return toHex(randomBytes(32));
      case '2':
        return await rli.question('Enter your wallet seed: ');
      case '3':
        logger.info('Exiting...');
        return undefined;
      default:
        logger.error(`Invalid choice: ${choice}`);
    }
  }
};

/* **********************************************************************
 * run: the main entry point that starts the whole course completion
 * credential CLI.
 *
 * If called with a Docker environment argument, the application
 * will wait for Docker to be ready before doing anything else.
 */

export const run = async (config: Config, testEnv: TestEnvironment, logger: Logger): Promise<void> => {
  const rli = createInterface({ input, output, terminal: true });
  const providersToBeStopped: MidnightWalletProvider[] = [];
  try {
    const envConfiguration = await testEnv.start();
    logger.info(`Environment started with configuration: ${JSON.stringify(envConfiguration)}`);
    const seed = await buildWallet(config, rli, logger);
    if (seed === undefined) {
      return;
    }
    const walletProvider = await MidnightWalletProvider.build(logger, envConfiguration, seed);
    providersToBeStopped.push(walletProvider);
    const walletFacade: WalletFacade = walletProvider.wallet;

    await walletProvider.start();

    const unshieldedState = await waitForUnshieldedFunds(logger, walletFacade, envConfiguration, unshieldedToken());
    const nightBalance = unshieldedState.balances[unshieldedToken().raw];
    if (nightBalance === undefined) {
      logger.info('No funds received, exiting...');
      return;
    }
    logger.info(`Your NIGHT wallet balance is: ${nightBalance}`);

    if (config.generateDust) {
      const dustGeneration = await generateDust(logger, seed, unshieldedState, walletFacade);
      if (dustGeneration) {
        logger.info(`Submitted dust generation registration transaction: ${dustGeneration}`);
        await syncWallet(logger, walletFacade);
      }
    }

    const zkConfigProvider = new NodeZkConfigProvider<'issueCredential' | 'revokeCredential'>(config.zkConfigPath);
    const providers: CourseCredentialProviders = {
      privateStateProvider: levelPrivateStateProvider<PrivateStateId, CourseCredentialPrivateState>({
        privateStateStoreName: config.privateStateStoreName,
        signingKeyStoreName: `${config.privateStateStoreName}-signing-keys`,
        privateStoragePasswordProvider: () => {
          return 'Bboard-Test-2026!';
        },
        accountId: seed,
      }),
      publicDataProvider: indexerPublicDataProvider(envConfiguration.indexer, envConfiguration.indexerWS),
      zkConfigProvider: zkConfigProvider,
      proofProvider: httpClientProofProvider(envConfiguration.proofServer, zkConfigProvider),
      walletProvider: walletProvider,
      midnightProvider: walletProvider,
    };
    await mainLoop(providers, rli, logger);
  } catch (e) {
    logError(logger, e);
    logger.info('Exiting...');
  } finally {
    try {
      rli.close();
      rli.removeAllListeners();
    } catch (e) {
      logError(logger, e);
    } finally {
      try {
        for (const wallet of providersToBeStopped) {
          logger.info('Stopping wallet...');
          await wallet.stop();
        }
        if (testEnv) {
          logger.info('Stopping test environment...');
          await testEnv.shutdown();
        }
      } catch (e) {
        logError(logger, e);
      }
    }
  }
};

function logError(logger: Logger, e: unknown) {
  if (e instanceof Error) {
    logger.error(`Found error '${e.message}'`);
    logger.debug(`${e.stack}`);
  } else {
    logger.error(`Found error (unknown type)`);
  }
}
