// This file is part of midnightntwrk/example-bboard.
// Copyright (C) Midnight Foundation
// SPDX-License-Identifier: Apache-2.0
// Licensed under the Apache License, Version 2.0 (the "License");
// You may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/**
 * Provides utility functions.
 *
 * @module
 */

/**
 * Generates a buffer containing a series of randomly generated bytes.
 *
 * @param length The number of bytes to generate.
 * @returns A `Uint8Array` representing `length` randomly generated bytes.
 */
export const randomBytes = (length: number): Uint8Array => {
  const bytes = new Uint8Array(length);
  crypto.getRandomValues(bytes);
  return bytes;
};

/**
 * Hashes an arbitrary string into a `Bytes<32>` value using SHA-256.
 *
 * @remarks
 * Compact's `persistentCommit` cannot hash opaque JavaScript strings directly, so
 * the student identifier is reduced to 32 bytes here (in the DApp layer) before it
 * is committed to on-chain. SHA-256 is available both in Node.js (global `crypto`)
 * and in browsers (Web Crypto API), so this helper works from the CLI and the UI.
 *
 * @param value The value to hash.
 * @returns A `Promise` that resolves to the 32-byte SHA-256 digest of `value`.
 */
export const hashToBytes32 = async (value: string): Promise<Uint8Array> => {
  const digest = await crypto.subtle.digest('SHA-256', new TextEncoder().encode(value.trim()));
  return new Uint8Array(digest);
};

/**
 * Converts a 64-character hex string (with or without '0x' prefix) into a 32-byte `Uint8Array`.
 *
 * @param hex The hexadecimal string to parse.
 * @returns A `Uint8Array` of length exactly 32.
 * @throws `Error` if the hex string is not a valid 32-byte representation.
 */
export const hexToBytes32 = (hex: string): Uint8Array => {
  const sanitized = hex.trim().replace(/^0x/i, '');
  if (!/^[0-9a-fA-F]{64}$/.test(sanitized)) {
    throw new Error(
      `Invalid salt: expected 64 hexadecimal characters (32 bytes), received '${hex.trim()}' (${sanitized.length} valid hex chars)`,
    );
  }
  const bytes = new Uint8Array(32);
  for (let i = 0; i < 32; i++) {
    bytes[i] = parseInt(sanitized.substring(i * 2, i * 2 + 2), 16);
  }
  return bytes;
};
